# Generated by Django 3.1.1 on 2021-03-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20210310_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(db_column='Music', default='', max_length=100, unique=True, verbose_name='Music')),
                ('plan', models.ForeignKey(db_column='Plan', on_delete=django.db.models.deletion.CASCADE, to='authentication.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name_plural': 'Musics',
            },
        ),
    ]
