# Generated by Django 3.1.1 on 2021-03-12 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auto_20210312_1448'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='plan',
            field=models.ForeignKey(db_column='Plan', on_delete=django.db.models.deletion.CASCADE, related_name='music_plan', to='authentication.plan', verbose_name='Plan'),
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(db_column='Music', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_music', to='playlist.music', verbose_name='Music')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'PlayList',
            },
        ),
    ]
