# Generated by Django 3.1.1 on 2021-03-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, db_column='Plan', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.plan', verbose_name='Plan'),
        ),
    ]
