# Generated by Django 3.1.1 on 2021-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210310_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(db_column='Plan', default='Basic', max_length=100, unique=True, verbose_name='Plan'),
        ),
    ]
