# Generated by Django 3.1.1 on 2021-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210310_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='priority',
            field=models.IntegerField(db_column='Priority', default=0, verbose_name='Priority'),
        ),
    ]
